name: Publish

on:
  workflow_dispatch:
    inputs:
      pypi:
        description: 'Publish to PyPI'
        type: boolean
        default: true
      github_release:
        description: 'Create GitHub Release'
        type: boolean
        default: true

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        enable-cache: true
    
    - name: Set up Python
      run: uv python install 3.12
    
    - name: Install dependencies
      run: uv sync --dev
    
    - name: Run tests
      run: uv run pytest
    
    - name: Build package
      run: uv build
    
    - name: Publish to PyPI
      if: ${{ inputs.pypi }}
      env:
        PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
      run: uv publish --token $PYPI_TOKEN
    
    - name: Create GitHub Release
      if: ${{ inputs.github_release }}
      uses: softprops/action-gh-release@v1
      with:
        files: dist/*
        generate_release_notes: true
        tag_name: v${{ github.run_number }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
